#!/usr/bin/env php
<?php
	require __DIR__.'/vendor/autoload.php';
	use Symfony\Component\Console\Application;
	use Symfony\Component\Console\Command\Command;
	use Symfony\Component\Console\Input\InputInterface;
	use Symfony\Component\Console\Input\InputOption;
	use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Component\Process\Process;
	

    class Server extends Command{
        protected function configure():void
		{
			$this
				->setName('serve')
				->setDescription('Start the development server.')
                ->addOption('host',null,InputOption::VALUE_OPTIONAL,'The host address to serve no','localhost')
                ->addOption('port',null,InputOption::VALUE_OPTIONAL,'The port to serve on','8000')
			;
		}
		
		protected function execute(InputInterface $input, OutputInterface $output):int
		{
			$host = $input->getOption('host');
			$port = $input->getOption('port');
			$output->writeln("Development server started on http://$host:$port");
			$process = new Process(["php", "-S", "$host:$port", "-t", "public"]);
			$process->setTimeout(null);
			$process->run(function ($type, $buffer) {
				echo $buffer;
			});


			return Command::SUCCESS;
		}
    }
	
  $application = new Application();
  $application->add(new Server());
  $application->run();
  
    